### PR TITLE
Feature/api improvements

### PR DESCRIPTION
**Pull request by tomtzook**
@ApatheticIdiot so made some changes.
Thoughts?

### CODE REVIEW

**Comment by tomtzook** [comment]
Code example:

```java
    public static void main(String[] args) {
        loadNatives();

        Mat originalImg = Imgcodecs.imread("/home/tomtzook/Downloads/tagformats_web.png");

        Mat gsImg = new Mat();
        Imgproc.cvtColor(originalImg, gsImg, Imgproc.COLOR_BGR2GRAY);

        try (Family family = new Family(FamilyType.TAGCIRCLE21H7); Detector detector = new Detector();) {
            detector.addFamily(family);
            try (Detections detections = detector.detect(gsImg)) {
                while (detections.hasNext()) {
                    Detection detection = detections.next();
                    Imgproc.putText(
                            originalImg,
                            String.valueOf(detection.id),
                            new Point(detection.centerX, detection.centerY),
                            Imgproc.FONT_HERSHEY_SCRIPT_SIMPLEX,
                            1.0,
                            new Scalar(0xff, 0x99, 0),
                            2
                    );
                }
            }
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

        JFrame frame = createWindow();
        JLabel lbl = createImageHolder(frame);
        frame.setVisible(true);
        showImage(lbl, originalImg);
    }
```

**Comment by tomtzook** [comment]
[apriltags4j-bin.zip](https://github.com/Flash3388/AprilTags4j/files/10059470/apriltags4j-bin.zip)
binaries built.

**Comment by tomtzook** [comment]
[apriltags4j-test.zip](https://github.com/Flash3388/AprilTags4j/files/10059479/apriltags4j-test.zip)
Example project.

**Comment by SpaceCowboyOren** [comment]
> @ApatheticIdiot so made some changes. Thoughts?
kinda goated ngl dude, bro, pal, buddy.

**Pull request merged**
